# Generated by Django 6.1 on 2026-08-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maintenancerepair",
            name="category",
            field=models.CharField(
                choices=[
                    ("plumbing", "Tuubooyinka"),
                    ("electricity", "Koronto"),
                    ("structure", "Dhismaha"),
                    ("appliance", "Qalab"),
                    ("other", "Kale"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="maintenancerepair",
            name="status",
            field=models.CharField(
                choices=[
                    ("reported", "La soo sheegay"),
                    ("in_progress", "Waa socotaa"),
                    ("fixed", "La hagaajiyay"),
                    ("cancelled", "La baajiyay"),
                ],
                default="reported",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Lacag caddaan ah"),
                    ("mobile_money", "Mobile Money"),
                    ("bank", "Bangiga"),
                    ("other", "Kale"),
                ],
                default="mobile_money",
                max_length=20,
            ),
        ),
    ]
