# Generated by Django 6.0 on 2026-09-01 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0001_initial"),
        ("finance", "0002_alter_maintenancerepair_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalexpense",
            name="expense_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="general_expenses",
                to="accounting.account",
            ),
        ),
        migrations.AddField(
            model_name="maintenancerepair",
            name="expense_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Xisaabta kharashka (tusaale: Kharashka Dayactirka)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="maintenance_repairs",
                to="accounting.account",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="destination_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Xisaabta lacagta lagu shubay (tusaale Bank ama Zaad)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="accounting.account",
            ),
        ),
    ]
