# Generated by Django 6.0 on 2026-09-03 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_generalexpense_expense_account_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="generalexpense",
            name="expense_account",
        ),
        migrations.RemoveField(
            model_name="maintenancerepair",
            name="expense_account",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="destination_account",
        ),
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(max_length=100, verbose_name="Magaca Bangiga"),
                ),
                (
                    "account_number",
                    models.CharField(max_length=50, verbose_name="Lambarka Xisaabta"),
                ),
                (
                    "account_name",
                    models.CharField(max_length=150, verbose_name="Magaca Xisaabta"),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("checking", "Xisaabta Lacagta (Checking)"),
                            ("savings", "Xisaabta Kaydka (Savings)"),
                            ("mobile", "Mobile Money"),
                            ("cash", "Lacag Caddaan ah"),
                        ],
                        default="checking",
                        max_length=20,
                        verbose_name="Nooca",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Hadhaaga",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Faahfaahin")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Waa shaqeyneysaa"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["bank_name"],
                "unique_together": {("owner", "account_number")},
            },
        ),
        migrations.AddField(
            model_name="generalexpense",
            name="bank_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Xisaabta lacagta laga bixiyay",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="general_expenses",
                to="finance.bankaccount",
            ),
        ),
        migrations.AddField(
            model_name="maintenancerepair",
            name="bank_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Xisaabta lacagta laga bixiyay",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="maintenance_repairs",
                to="finance.bankaccount",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="bank_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Xisaabta lacagta lagu shubay",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="finance.bankaccount",
            ),
        ),
    ]
