# Generated by Django 6.0 on 2026-09-03 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0004_remove_generalexpense_expense_account_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bankaccount",
            name="account_type",
        ),
        migrations.RemoveField(
            model_name="bankaccount",
            name="balance",
        ),
    ]
