# Generated by Django 6.0 on 2026-09-03 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0003_account_bank_account_alter_account_category_and_more"),
        ("finance", "0005_remove_bankaccount_account_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="linked_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Xisaabta Accounting-ka ee bangigan",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_bank_accounts",
                to="accounting.account",
            ),
        ),
        migrations.AddField(
            model_name="generalexpense",
            name="expense_account",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"category": "expense"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="general_expenses",
                to="accounting.account",
            ),
        ),
        migrations.AddField(
            model_name="generalexpense",
            name="journal_entry",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="general_expense_source",
                to="accounting.journalentry",
            ),
        ),
        migrations.AddField(
            model_name="maintenancerepair",
            name="expense_account",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"category": "expense"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="maintenance_repairs",
                to="accounting.account",
            ),
        ),
        migrations.AddField(
            model_name="maintenancerepair",
            name="journal_entry",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="repair_source",
                to="accounting.journalentry",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="destination_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Xisaabta lacagta lagu shubay",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments_received",
                to="accounting.account",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="accounting.invoice",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="journal_entry",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_source",
                to="accounting.journalentry",
            ),
        ),
        migrations.AlterField(
            model_name="generalexpense",
            name="bank_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="general_expenses",
                to="finance.bankaccount",
            ),
        ),
        migrations.AlterField(
            model_name="maintenancerepair",
            name="bank_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="maintenance_repairs",
                to="finance.bankaccount",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="bank_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="finance.bankaccount",
            ),
        ),
    ]
