# Generated by Django 6.0 on 2026-09-05 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0006_bankaccount_linked_account_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalexpense",
            name="payment_status",
            field=models.CharField(
                choices=[("unpaid", "Aan la bixin"), ("paid", "La bixiyay")],
                default="unpaid",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="maintenancerepair",
            name="payment_status",
            field=models.CharField(
                choices=[("unpaid", "Aan la bixin"), ("paid", "La bixiyay")],
                default="unpaid",
                max_length=10,
            ),
        ),
    ]
