# Generated by Django 6.0 on 2026-10-01 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounting",
            "0007_alter_account_bank_account_alter_account_category_and_more",
        ),
        ("finance", "0008_chatsession_chatmessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankaccount",
            name="account_name",
            field=models.CharField(max_length=150, verbose_name="Account name"),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="account_number",
            field=models.CharField(max_length=50, verbose_name="Account number"),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="bank_name",
            field=models.CharField(max_length=100, verbose_name="Bank name"),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is active"),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="linked_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Linked accounting ledger account (optional)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_bank_accounts",
                to="accounting.account",
            ),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Notes"),
        ),
        migrations.AlterField(
            model_name="generalexpense",
            name="payment_status",
            field=models.CharField(
                choices=[("unpaid", "Unpaid"), ("paid", "Paid")],
                default="unpaid",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="maintenancerepair",
            name="category",
            field=models.CharField(
                choices=[
                    ("plumbing", "Plumbing"),
                    ("electricity", "Electricity"),
                    ("structure", "Structure"),
                    ("appliance", "Appliance"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="maintenancerepair",
            name="payment_status",
            field=models.CharField(
                choices=[("unpaid", "Unpaid"), ("paid", "Paid")],
                default="unpaid",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="maintenancerepair",
            name="status",
            field=models.CharField(
                choices=[
                    ("reported", "Reported"),
                    ("in_progress", "In progress"),
                    ("fixed", "Fixed"),
                    ("cancelled", "Cancelled"),
                ],
                default="reported",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="destination_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Account the payment was deposited into",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments_received",
                to="accounting.account",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("mobile_money", "Mobile Money"),
                    ("bank", "Bank"),
                    ("other", "Other"),
                ],
                default="mobile_money",
                max_length=20,
            ),
        ),
    ]
