# Generated by Django 6.1.1 on 2026-10-08 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0009_alter_invoice_invoice_number_and_more"),
        ("finance", "0009_alter_bankaccount_account_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="accounting.invoice",
            ),
        ),
    ]
