# Generated by Django 6.1 on 2026-08-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rentalagreement",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Socda"),
                    ("ended", "Dhammaaday"),
                    ("cancelled", "La baajiyay"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="full_name",
            field=models.CharField(
                max_length=150, verbose_name="Magaca qofka ama qoyska"
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="tenant_type",
            field=models.CharField(
                choices=[("person", "Qof ama qoys"), ("business", "Ganacsi")],
                default="person",
                max_length=20,
            ),
        ),
    ]
