# Generated by Django 6.1 on 2026-08-27 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0004_remove_unit_default_monthly_rent_unit_bathrooms_and_more"),
        (
            "rentals",
            "0002_alter_rentalagreement_status_alter_tenant_full_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="rentalagreement",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rental_agreements",
                to="properties.room",
            ),
        ),
        migrations.AlterField(
            model_name="rentalagreement",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rental_agreements",
                to="properties.unit",
            ),
        ),
        migrations.AddConstraint(
            model_name="rentalagreement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("unit__isnull", False), ("room__isnull", True)),
                    models.Q(("unit__isnull", True), ("room__isnull", False)),
                    _connector="OR",
                ),
                name="agreement_has_one_rentable_space",
            ),
        ),
    ]
