# Generated by Django 6.1 on 2026-08-27 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0005_property_total_rentable_spaces"),
        ("rentals", "0003_rentalagreement_room_alter_rentalagreement_unit_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="rentalagreement",
            name="agreement_has_one_rentable_space",
        ),
        migrations.AddField(
            model_name="rentalagreement",
            name="agreed_monthly_rent",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="rentalagreement",
            name="property",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rental_agreements",
                to="properties.property",
            ),
        ),
        migrations.AddField(
            model_name="rentalagreement",
            name="rental_scope",
            field=models.CharField(
                choices=[
                    ("whole_property", "Hantida oo dhan"),
                    ("partial_property", "Qeyb ka mid ah"),
                ],
                default="whole_property",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="rentalagreement",
            name="rented_space_count",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name="rentalagreement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("property__isnull", False),
                    ("unit__isnull", False),
                    ("room__isnull", False),
                    _connector="OR",
                ),
                name="agreement_has_rentable_space",
            ),
        ),
    ]
