# Generated by Django 6.1 on 2026-08-27 13:16

from django.conf import settings
from django.db import migrations, models


def merge_duplicate_tenants(apps, schema_editor):
    Tenant = apps.get_model("rentals", "Tenant")
    Agreement = apps.get_model("rentals", "RentalAgreement")
    duplicates = Tenant.objects.values("owner_id", "phone_number").annotate(total=models.Count("id")).filter(total__gt=1)
    for group in duplicates:
        tenants = list(Tenant.objects.filter(owner_id=group["owner_id"], phone_number=group["phone_number"]).order_by("id"))
        primary, duplicate_tenants = tenants[0], tenants[1:]
        Agreement.objects.filter(tenant_id__in=[tenant.id for tenant in duplicate_tenants]).update(tenant_id=primary.id)
        Tenant.objects.filter(id__in=[tenant.id for tenant in duplicate_tenants]).delete()


class Migration(migrations.Migration):

    dependencies = [
        (
            "rentals",
            "0004_remove_rentalagreement_agreement_has_one_rentable_space_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.RunPython(merge_duplicate_tenants, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="tenant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("phone_number", ""), _negated=True),
                fields=("owner", "phone_number"),
                name="unique_tenant_phone_per_owner",
            ),
        ),
    ]
