# Generated by Django 6.0 on 2026-09-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0005_alter_tenant_phone_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rentalagreement",
            name="electricity_responsible",
            field=models.CharField(
                choices=[("customer", "Customer pays"), ("company", "Company pays")],
                default="customer",
                max_length=10,
                verbose_name="Who pays electricity",
            ),
        ),
        migrations.AddField(
            model_name="rentalagreement",
            name="final_bills_notes",
            field=models.TextField(blank=True, verbose_name="Final bills notes"),
        ),
        migrations.AddField(
            model_name="rentalagreement",
            name="final_bills_settlement",
            field=models.CharField(
                choices=[
                    ("not_checked", "Not checked"),
                    ("paid", "Paid before leaving"),
                    ("unpaid", "Unpaid"),
                ],
                default="not_checked",
                max_length=12,
                verbose_name="Final bills settlement",
            ),
        ),
        migrations.AddField(
            model_name="rentalagreement",
            name="water_responsible",
            field=models.CharField(
                choices=[("customer", "Customer pays"), ("company", "Company pays")],
                default="customer",
                max_length=10,
                verbose_name="Who pays water",
            ),
        ),
    ]
