# Generated by Django 6.0 on 2026-10-01 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0006_rentalagreement_electricity_responsible_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rentalagreement",
            name="rental_scope",
            field=models.CharField(
                choices=[
                    ("whole_property", "Whole property"),
                    ("partial_property", "Part of property"),
                ],
                default="whole_property",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="rentalagreement",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("ended", "Ended"),
                    ("cancelled", "Cancelled"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="full_name",
            field=models.CharField(max_length=150, verbose_name="Full name"),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="tenant_type",
            field=models.CharField(
                choices=[("person", "Person or family"), ("business", "Business")],
                default="person",
                max_length=20,
            ),
        ),
    ]
