# Generated by Django 6.1 on 2026-08-27 06:31

from django.db import migrations, models


def copy_phone_to_username(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    for user in User.objects.filter(username__isnull=True):
        user.username = user.phone_number
        user.save(update_fields=["username"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.RunPython(copy_phone_to_username, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="user",
            name="full_name",
            field=models.CharField(max_length=150, verbose_name="Magaca oo buuxa"),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
