# Generated by Django 6.1 on 2026-09-04 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_is_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="managed_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Dooro akoonka uu isticmaalahani maamulayo xogtiisa (Tusaale: Farxaan).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_users",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Sii gelitaanka akoonka (Managed Account)",
            ),
        ),
    ]
