# Generated by Django 6.0 on 2026-09-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_managed_account"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gemini_api_key",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Gemini API Key",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="can_use_chatbot",
            field=models.BooleanField(
                default=False,
                help_text="Ikhtiyaari: Ogolow isticmaalahan inuu isticmaalo AI Chatbot",
                verbose_name="AI Chatbot",
            ),
        ),
    ]
