# Generated by Django 6.0 on 2026-10-01 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_sitesettings_user_can_use_chatbot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="can_use_chatbot",
            field=models.BooleanField(
                default=False,
                help_text="Optional: allow this user to use the AI Chatbot",
                verbose_name="AI Chatbot",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="full_name",
            field=models.CharField(max_length=150, verbose_name="Full name"),
        ),
        migrations.AlterField(
            model_name="user",
            name="managed_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Choose the account whose data this user manages (e.g. Farxaan).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_users",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Managed account",
            ),
        ),
    ]
