# Generated by Django 6.1 on 2026-08-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="name",
            field=models.CharField(max_length=150, verbose_name="Magaca hantida"),
        ),
        migrations.AlterField(
            model_name="property",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("residential", "Guri degaan"),
                    ("commercial", "Ganacsi"),
                    ("mixed", "Isku-dhafan"),
                ],
                default="residential",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="unit_type",
            field=models.CharField(
                choices=[
                    ("house", "Guri"),
                    ("apartment", "Aqal"),
                    ("room", "Qol"),
                    ("shop", "Dukaan"),
                    ("office", "Xafiis"),
                    ("other", "Kale"),
                ],
                default="apartment",
                max_length=20,
            ),
        ),
    ]
