# Generated by Django 6.1 on 2026-08-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "properties",
            "0002_alter_property_name_alter_property_property_type_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="cover_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="property_covers/"
            ),
        ),
    ]
