# Generated by Django 6.1 on 2026-08-27 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0003_property_cover_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="unit",
            name="default_monthly_rent",
        ),
        migrations.AddField(
            model_name="unit",
            name="bathrooms",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="unit",
            name="living_rooms",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="unit",
            name="monthly_rent",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="unit",
            name="rental_mode",
            field=models.CharField(
                choices=[
                    ("whole_unit", "Guriga oo dhan"),
                    ("individual_rooms", "Qolal gaar-gaar ah"),
                ],
                default="whole_unit",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="total_rooms",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_name", models.CharField(max_length=50)),
                ("monthly_rent", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="properties.unit",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("unit", "room_name"), name="unique_room_per_unit"
                    )
                ],
            },
        ),
    ]
