# Generated by Django 6.1 on 2026-08-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0004_remove_unit_default_monthly_rent_unit_bathrooms_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="total_rentable_spaces",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
