# Generated by Django 6.1 on 2026-08-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0005_property_total_rentable_spaces"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("home", "Guri"),
                    ("apartment", "Apartment"),
                    ("commercial", "Ganacsi"),
                    ("mixed", "Isku-dhafan"),
                ],
                default="home",
                max_length=20,
            ),
        ),
    ]
