# Generated by Django 6.0 on 2026-08-31 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0006_alter_property_property_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Magaca alaabta"),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("good", "Fiican"),
                            ("needs_repair", "Dayactir u baahan"),
                            ("damaged", "Waxyeelloobay"),
                            ("missing", "Maqan"),
                        ],
                        default="good",
                        max_length=20,
                    ),
                ),
                (
                    "responsible_party",
                    models.CharField(
                        choices=[
                            ("owner", "Milkiilaha"),
                            ("tenant", "Kiraystaha"),
                            ("shared", "Labada dhinac"),
                        ],
                        default="tenant",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
