# Generated by Django 6.0 on 2026-08-31 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0007_propertyasset"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="room_type",
            field=models.CharField(
                choices=[
                    ("living_room", "Qolka fadhiga"),
                    ("bedroom", "Qolka jiifka"),
                    ("bathroom", "Musqusha"),
                    ("kitchen", "Jikada"),
                    ("office", "Xafiiska"),
                    ("other", "Qol kale"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="floor_number",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
