# Generated by Django 6.0 on 2026-08-31 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0008_room_room_type_unit_floor_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="residential_structure",
            field=models.CharField(
                choices=[("villa", "Filo"), ("multi_floor", "Guri dabaq")],
                default="villa",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="unit_type",
            field=models.CharField(
                choices=[
                    ("house", "Guri"),
                    ("apartment", "Apartment"),
                    ("room", "Qol"),
                    ("shop", "Dukaan"),
                    ("office", "Xafiis"),
                    ("other", "Kale"),
                ],
                default="apartment",
                max_length=20,
            ),
        ),
    ]
