# Generated by Django 6.0 on 2026-09-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0009_property_residential_structure_alter_unit_unit_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="electricity_account_no",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Electricity account no."
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="water_account_no",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Water account no."
            ),
        ),
    ]
