# Generated by Django 6.0 on 2026-10-01 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0010_property_electricity_account_no_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="name",
            field=models.CharField(max_length=150, verbose_name="Property name"),
        ),
        migrations.AlterField(
            model_name="property",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("home", "Home"),
                    ("apartment", "Apartment"),
                    ("commercial", "Commercial"),
                    ("mixed", "Mixed"),
                ],
                default="home",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="residential_structure",
            field=models.CharField(
                choices=[("villa", "Villa"), ("multi_floor", "Multi-floor building")],
                default="villa",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="propertyasset",
            name="condition",
            field=models.CharField(
                choices=[
                    ("good", "Good"),
                    ("needs_repair", "Needs repair"),
                    ("damaged", "Damaged"),
                    ("missing", "Missing"),
                ],
                default="good",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="propertyasset",
            name="name",
            field=models.CharField(max_length=150, verbose_name="Item name"),
        ),
        migrations.AlterField(
            model_name="propertyasset",
            name="responsible_party",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("tenant", "Customer"),
                    ("shared", "Shared"),
                ],
                default="tenant",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_type",
            field=models.CharField(
                choices=[
                    ("living_room", "Living room"),
                    ("bedroom", "Bedroom"),
                    ("bathroom", "Bathroom"),
                    ("kitchen", "Kitchen"),
                    ("office", "Office"),
                    ("other", "Other room"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="rental_mode",
            field=models.CharField(
                choices=[
                    ("whole_unit", "Whole unit"),
                    ("individual_rooms", "Individual rooms"),
                ],
                default="whole_unit",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="unit_type",
            field=models.CharField(
                choices=[
                    ("house", "House"),
                    ("apartment", "Apartment"),
                    ("room", "Room"),
                    ("shop", "Shop"),
                    ("office", "Office"),
                    ("other", "Other"),
                ],
                default="apartment",
                max_length=20,
            ),
        ),
    ]
