# Generated by Django 6.0 on 2026-09-01 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("properties", "0009_property_residential_structure_alter_unit_unit_type"),
        ("rentals", "0005_alter_tenant_phone_number_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, verbose_name="Koodhka")),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Magaca Xisaabta"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("asset", "Asset (Hanti)"),
                            ("liability", "Liability (Deyn)"),
                            ("equity", "Equity (Raasamaal)"),
                            ("revenue", "Revenue (Dakhli)"),
                            ("expense", "Expense (Kharash)"),
                        ],
                        max_length=20,
                        verbose_name="Qaybta",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Faahfaahin"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Waa Shaqeyneysaa"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
                "unique_together": {("owner", "code")},
            },
        ),
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Taariikhda")),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Tixraac"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Faahfaahin"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Qabyo"),
                            ("posted", "La diiwaangeliyay"),
                            ("cancelled", "La baajiyay"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Xaaladda",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journal_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="journal_entries",
                        to="rentals.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JournalEntryLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Faahfaahin"
                    ),
                ),
                (
                    "debit",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="Debit"
                    ),
                ),
                (
                    "credit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Credit",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="journal_lines",
                        to="accounting.account",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="accounting.journalentry",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="journal_lines",
                        to="properties.property",
                    ),
                ),
            ],
        ),
    ]
