# Generated by Django 6.0 on 2026-09-01 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0001_initial"),
        ("properties", "0009_property_residential_structure_alter_unit_unit_type"),
        ("rentals", "0005_alter_tenant_phone_number_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Numbarka Biilka"
                    ),
                ),
                ("date", models.DateField(verbose_name="Taariikhda Biilka")),
                (
                    "due_date",
                    models.DateField(verbose_name="Taariikhda Kama Dambaysta ah"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Qabyo"),
                            ("sent", "La diray"),
                            ("paid", "La bixiyay"),
                            ("cancelled", "La baajiyay"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Xaaladda",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Faahfaahin")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "journal_entry",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoice",
                        to="accounting.journalentry",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="properties.property",
                    ),
                ),
                (
                    "rental_agreement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="rentals.rentalagreement",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="rentals.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InvoiceLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Faahfaahin"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Lacagta"
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        help_text="Xisaabta Dakhliga (Revenue Account)",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoice_lines",
                        to="accounting.account",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="accounting.invoice",
                    ),
                ),
            ],
        ),
    ]
