# Generated by Django 6.0 on 2026-09-03 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0002_invoice_invoiceline"),
        ("finance", "0005_remove_bankaccount_account_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="bank_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Xisoabta Bangiga ee la xiriirta (ikhtiyaari)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accounting_accounts",
                to="finance.bankaccount",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="category",
            field=models.CharField(
                choices=[
                    ("asset", "Hanti (Asset) - Wixii aad leedahay"),
                    ("liability", "Deyn (Liability) - Wixii aad iska leedahay"),
                    ("equity", "Raasamaal (Equity) - Net-worth-kaaga"),
                    ("revenue", "Dakhli (Revenue) - Wixii aad ku heshay"),
                    ("expense", "Kharash (Expense) - Wixii aad ku bixisay"),
                ],
                max_length=20,
                verbose_name="Qaybta",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="code",
            field=models.CharField(max_length=20, verbose_name="Lambarka"),
        ),
    ]
