# Generated by Django 6.0 on 2026-09-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0005_fix_localization_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="category",
            field=models.CharField(
                choices=[
                    ("asset", "Hanti (Asset) - Wixii aad leedahay"),
                    ("liability", "Deyn (Liability) - Wixii lagugu leeyahay"),
                    ("equity", "Raasamaal (Equity) - Net-worth-kaaga"),
                    ("revenue", "Dakhli (Revenue) - Wixii aad ku heshay"),
                    ("expense", "Kharash (Expense) - Wixii aad ku bixisay"),
                ],
                max_length=20,
                verbose_name="Qaybta",
            ),
        ),
    ]
