# Generated by Django 6.0 on 2026-10-01 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0006_alter_account_category"),
        ("finance", "0008_chatsession_chatmessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="bank_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Linked bank account (optional)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accounting_accounts",
                to="finance.bankaccount",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="category",
            field=models.CharField(
                choices=[
                    ("asset", "Hanti (Asset) - Wixii aad leedahay"),
                    ("liability", "Deyn (Liability) - Wixii lagugu leeyahay"),
                    ("equity", "Raasamaal (Equity) - Net-worth-kaaga"),
                    ("revenue", "Dakhli (Revenue) - Wixii aad ku heshay"),
                    ("expense", "Kharash (Expense) - Wixii aad ku bixisay"),
                ],
                max_length=20,
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="code",
            field=models.CharField(max_length=20, verbose_name="Code"),
        ),
        migrations.AlterField(
            model_name="account",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="account",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is active"),
        ),
        migrations.AlterField(
            model_name="account",
            name="is_system",
            field=models.BooleanField(
                default=False,
                help_text="System accounts cannot be deleted",
                verbose_name="System account",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="name",
            field=models.CharField(max_length=150, verbose_name="Account name"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="date",
            field=models.DateField(verbose_name="Invoice date"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="due_date",
            field=models.DateField(verbose_name="Due date"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoice_number",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Invoice number"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Notes"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("sent", "Sent"),
                    ("paid", "Paid"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="invoiceline",
            name="account",
            field=models.ForeignKey(
                help_text="Revenue account",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoice_lines",
                to="accounting.account",
            ),
        ),
        migrations.AlterField(
            model_name="invoiceline",
            name="description",
            field=models.CharField(max_length=255, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="date",
            field=models.DateField(verbose_name="Date"),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="reference",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Reference"
            ),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("posted", "Posted"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="journalentryline",
            name="description",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Description"
            ),
        ),
    ]
