# Generated by Django 6.1.1 on 2026-10-06 09:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0008_translate_stored_descriptions"),
        ("properties", "0013_move_has_units_to_propertytype"),
        ("rentals", "0007_alter_rentalagreement_rental_scope_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="invoice_number",
            field=models.CharField(max_length=50, verbose_name="Invoice number"),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                fields=("owner", "invoice_number"),
                name="unique_invoice_number_per_owner",
            ),
        ),
    ]
